# Generated by Django 2.2.6 on 2020-03-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('animal_code', models.CharField(max_length=10)),
            ],
        ),
    ]
